### ISSUE TITLE
column of transparent pixels

### ISSUE THREAD

**Issue by gilbertohasnofb** [satyarth/pixelsort#6] opened 2017-11-22 01:40 UTC
When using your program with the option `-a 90`, the first column of pixels is always completely transparent. This is not observed when this argument is not present (i.e. horizontal mode).

**Comment by satyarth** [comment] 2017-11-22 01:41
Thanks for the issue, I'll (hopefully) take a look at it soon.

**Comment by gilbertohasnofb** [comment] 2017-11-22 01:42
Thanks for the quick response! Please let me know if you need more information or if you can't reproduce the issue.

**Comment by abetusk** [comment] 2019-11-10 10:18
A little more info on this:

When using Python 3+ I cannot reproduce this error.

I get the 'line of blank pixels' using my version of Python 2 (`$ python --version: Python 2.7.12`).

Googling around, I can't find any reference to this issue for Python2 with PIL, Image.rotate and not allowing center.

I've attached all the test images in question. For completeness, here is the command to (successfully) rotate the image in Python 3+ without the stray blank line:

```
$ python3 pixelsort.py -a 90 tt.png -o tt90_p3.png
```

So, from where I stand:

* **QUICK FIX**: just use `Python3`
* *better fix*: figure out what's going on with Python2 and make a compatible fix that works for both `Python2` and `Python3`

Please let me know if I've missed anything. I'm stumbling around with this stuff as I don't have intimate knowledge of Python.

| Image | Description |
|---|---|
| ![tt](https://user-images.githubusercontent.com/1406122/68542257-d56ef900-0378-11ea-9f06-ba9ead431205.png) | Original image |
| ![tt90_p2](https://user-images.githubusercontent.com/1406122/68542258-d56ef900-0378-11ea-81cb-f44b87a70290.png) | `python2 -a 90 tt.png -o tt_p2.png` |
| ![tt90_p3](https://user-images.githubusercontent.com/1406122/68542259-d6078f80-0378-11ea-9017-e10570420f23.png) | `python3 -a 90 tt.png -o tt_p3.png` |

**Comment by BernardZhao** [comment] 2021-03-11 22:51
Since python2 has long sunsetted I'm going to close this issue

**Closed as completed by BernardZhao** 2021-03-11 22:51 UTC
